### ISSUE TITLE
OJP 2.0 LIR "Bern" + Restrictions.NumberOfResults=10 return more than 10 places

### ISSUE THREAD

**Issue by vasile** [openTdataCH/ojp-sdk#11]
https://tools.odpch.ch/ojp-api-explorer-v2/?gist=d19270a6e71910a25ff6baa8173a4072

<img height="400" alt="image" src="https://github.com/openTdataCH/ojp-sdk/assets/113994/19d5b9cf-0a22-4fb0-b3ec-357705b5aa90">

Request
`/POST https://api.opentransportdata.swiss/ojp20`
XML: https://gist.github.com/vasile/d19270a6e71910a25ff6baa8173a4072

**Comment by TO-mdv** [comment]
@vasile the reason for this is, that Places with the same match quality (Probability) are in the response as well, we cannot filter them out because we don't know which of the 10th match is more relevant for the customer. So, in some cases it could be you get more results than expected.
![image](https://github.com/openTdataCH/ojp-sdk/assets/72090402/51569a87-d9af-43e3-8bcb-374f71374dcc)
