### ISSUE TITLE
Improve LIR 2-letter search

### ISSUE THREAD

**Issue by vasile** [openTdataCH/ojp-sdk#37]
Follow-up from #8 

BLS Mobile (Hafas backend) is returning meaningful results, can we achieve the same with OJP?

<img width="300" src="https://github.com/openTdataCH/ojp-sdk/assets/113994/cbf40066-c1c0-4667-a219-4407360268c8"/>

**Comment by vasile** [comment]
Check search.ch as reference for 1-2 letter search
https://search.ch/timetable/

**Comment by r3to** [comment]
@vasile and @TO-mdv can this be closed? IMO, the results have improved a lot in the last iteration

**Comment by vasile** [comment]
I think there is still room for improvement, i.e. for 1-2 letter search but up to you

**Comment by TO-mdv** [comment]
For the input `ba` and filter `stop` and `address ` you will still get no results, because the number of potential results exceed an internal limit. 
So if you really want to have results for inputs like that, we will need to make a bigger change in the code. So this issue must stay in backlog and priorized by @u233336. Or, if it's not that important for you, you can close it.

**Comment by u233336** [comment]
For the moment it seems to be OK for everyone (except the two letter search).
So I close the ticket.
