### ISSUE TITLE
Agree on a minimal LIR response XML

### ISSUE THREAD

**Issue by vasile** [openTdataCH/ojp-sdk#6]
In order that mobile SDKs to function correctly we need to agree on the minimal LIR response nodes that the OJP 2.0 will provide

Request XML is of BBOX GeoRestriction / Name InitialInput type with a Restriction on Type=`stop`

Current suggestion: https://github.com/openTdataCH/ojp-ios/blob/main/Tests/OJPTests/Resources/lir-minimum-response.xml

**Comment by TO-mdv** [comment]
see also my mail from 24.4.2024:
Data must always be present for the <StopPlaceRef> and <StopPlaceName> elements, otherwise our import will already cause problems.
A value is currently available for each stop for the <Name> element (city, municipality). We check this after each data preparation and, if necessary, it is corrected manually if the place cannot be found automatically. However, as manual checks and adjustments are necessary here, it is possible that the element is missing.

In addition, we have had cases in the past, as well as today, where stops do not have coordinates in the data supplied to us. The <GeoPosition> element will then be missing in the OJP2.0 response.
A current example is 8304701 Genova P. P. Sotterranea; INFO+ does not provide us with any coordinates for this stop.

I would therefore make the <GeoPosition> and <Name> elements optional for your minimum response to be on the safe side.

**Comment by r3to** [comment]
@TO-mdv thanks for documenting it here

I've just tested against Int and get a 500 when searching for "Genova"

```xml
<OJP xmlns="http://www.vdv.de/ojp" version="2.0" xmlns:siri="http://www.siri.org.uk/siri" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <OJPRequest>
        <siri:ServiceRequest>
            <siri:RequestTimestamp>2024-04-30T12:51:29Z</siri:RequestTimestamp>
            <siri:RequestorRef>OJP_Demo_iOS_IOS_SDK_0.0.1</siri:RequestorRef>
            <OJPLocationInformationRequest>
                <siri:RequestTimestamp>2024-04-30T12:51:29Z</siri:RequestTimestamp>
                <InitialInput>
                    <Name>genova</Name>
                </InitialInput>
                <Restrictions>
                    <Type>stop</Type>
                    <NumberOfResults>10</NumberOfResults>
                    <IncludePtModes>true</IncludePtModes>
                </Restrictions>
            </OJPLocationInformationRequest>
        </siri:ServiceRequest>
    </OJPRequest>
</OJP>
```

To re-create the request see https://gist.github.com/r3to/25a6314b930dd204a68cb5ad46db6bcf

**Comment by r3to** [comment]
According to the [generated docs from VDV](https://vdvde.github.io/OJP/develop/index.html#PlaceStructure=)
both `GeoPostion` and `Name` are mandatory fields

![image](https://github.com/openTdataCH/ojp-sdk/assets/105666/5829005a-7158-4b68-b56c-19abd3618ff2)

**Comment by vasile** [comment]
@TO-mdv lets try to conform to the schema and at import time to discard entries without GeoPosition and Name or just not show them in the response. @AndreasAtSBB will follow up with a dedicated discussion

**Comment by vasile** [comment]
Created #20
